<?php

namespace Yomen\AccountsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseEntityRepository extends EntityRepository
{
    public function ownedBy($owner, \Doctrine\ORM\QueryBuilder $qb = null)
    {
        if (is_null($qb)) {
            $qb = $this->createQueryBuilder('a');
        }
        $qb->andWhere('a.owner.id = :owner_id')
          ->setParameter('owner_id', $owner->getId());  
        return $qb;
    }

}
