operation:
    pattern:  /
    defaults: { _controller: "YomenAccountsBundle:Operation:index" }

operation_show:
    pattern:  /{id}/show
    defaults: { _controller: "YomenAccountsBundle:Operation:show" }

operation_new:
    pattern:  /new
    defaults: { _controller: "YomenAccountsBundle:Operation:new" }

operation_create:
    pattern:  /create
    defaults: { _controller: "YomenAccountsBundle:Operation:create" }
    requirements: { _method: post }

operation_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "YomenAccountsBundle:Operation:edit" }

operation_update:
    pattern:  /{id}/update
    defaults: { _controller: "YomenAccountsBundle:Operation:update" }
    requirements: { _method: post|put }

operation_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "YomenAccountsBundle:Operation:delete" }
    requirements: { _method: post|delete }
