comptes_cpt_homepage:
    pattern:  /
    defaults: { _controller: ComptesCptBundle:Comptes:index }

comptes_test:
    pattern:  /hello-{name}
    defaults: { _controller: ComptesCptBundle:Comptes:page }
