parameters:
#    yomen_category.example.class: Yomen\CategoryBundle\Example

services:
#    yomen_category.example:
#        class: %yomen_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
